name: .NET Core CI/CD
on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        configuration: [ Debug, Release ]
        include:
          - os: ubuntu-latest
            configuration: Release
            is-main: true
          - os: windows-latest
            configuration: Release
            is-netfx: true
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
   steps:
      - uses: actions/checkout@master
      - name: Build
        run: dotnet build -c ${{ matrix.configuration }}

      - name: Test
        run: dotnet test -c ${{ matrix.configuration }} --no-restore --collect:"XPlat Code Coverage" --settings coverlet.runsettings
          